/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1d',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#a1d494',
        'surface-tint': '#3b6934',
        'on-primary-fixed-variant': '#23501e',
        'tertiary-container': '#694932',
        'primary-container': '#2d5a27',
        'tertiary-fixed-dim': '#eabda0',
        'surface-container-low': '#f3f4f5',
        'surface-bright': '#f8f9fa',
        'primary-fixed': '#bcf0ae',
        'inverse-on-surface': '#f0f1f2',
        outline: '#72796e',
        'on-tertiary-container': '#e6ba9d',
        'on-primary-container': '#9dd090',
        'on-tertiary': '#ffffff',
        background: '#f8f9fa',
        surface: '#f8f9fa',
        'surface-container': '#edeeef',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#271900',
        'tertiary-fixed': '#ffdcc6',
        'on-surface-variant': '#42493e',
        'surface-dim': '#d9dadb',
        'secondary-container': '#fdc65c',
        'on-error': '#ffffff',
        primary: '#154212',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'outline-variant': '#c2c9bb',
        secondary: '#7c5800',
        'inverse-surface': '#2e3132',
        'on-tertiary-fixed': '#2d1604',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1d',
        'inverse-primary': '#a1d494',
        'secondary-fixed-dim': '#f4be55',
        'on-primary-fixed': '#002201',
        'on-secondary-container': '#745200',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed': '#ffdea7',
        tertiary: '#4f321d',
        'on-secondary-fixed-variant': '#5e4200',
        'surface-container-high': '#e7e8e9',
        'surface-variant': '#e1e3e4',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#5f402a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'stack-md': '16px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'section-padding': '80px',
        'stack-sm': '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Manrope', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'label-caps': ['Work Sans', 'sans-serif'],
        'display-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
